version: '3.4'

services:

  oracle:
    build: oracle
    image: oracle:11-xe
    container_name: oracle
    ports:
      - "1521:1521"
    environment:
      MSSQL_SA_PASSWORD: Forever21!
      ACCEPT_EULA: Y
    volumes:
      - .:/usr/local/src  

  java7:
    depends_on: 
      - oracle
    build: java/java7
    image: java:7
    container_name: java7
    volumes:
      - .:/usr/local/src 
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/local/src/service/code

  java8:
    depends_on: 
      - oracle
    build: java/java8
    image: java:8
    container_name: java8
    volumes:
      - .:/usr/local/src 
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/local/src/service/code

  service:
    build: service
    container_name: service
    volumes:
      - .:/usr/local/src
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /usr/local/src
