name: CI

on:
  push:
    branches:
      - master

jobs:

  info:
    name: about docker
    runs-on: ubuntu-latest
    steps:
    - name: versions
      run: |
        docker version
        docker-compose version
  tests:
    needs: info
    name: run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        export DIR=$(pwd)
        docker-compose up service
